### ISSUE TITLE
Not an issue, but a request.

### ISSUE THREAD

**Issue by karl0ss** [softplus/esp8266-wifi-timing#1]
This is a great write up, and perfect for a Wifi button I am making running off batteries, Idea is to press button, boot, send mqtt message, so seems perfect for what you have come up with..

I am trying to get the MQTT publish working in your existing code, and seem to be struggling, I notice you mention that you were doing (it would seem the exact thing I wanted) it already, but could you possibly publish the code you used to send the mqtt message after the successful connection?

Thank you

**Comment by softplus** [comment]
I should probably combine or clean this one up at some point, but I have a working implementation of this at https://github.com/softplus/esp01-fast-button that does the wifi connection & MQTT publishing. The MQTT code ( https://github.com/softplus/esp01-fast-button/blob/main/src/mqtt_helper.cpp ) uses the PubSubClient library to handle MQTT.

**Comment by karl0ss** [comment]
Thanks for your response, I ended up getting it working, but it would seem you have pretty much built what I was thinking already, though I may fork this and rework it to do deepsleep, as my intention is for this to be battery powered on a esp12f..

Thanks for all your great work
